#!/usr/bin/env python3

# Connect only a single Pololu Qik to the UART and run this script to configure it.
# ./configure_driver.py <device_id>
# Use device_id = 0 if you only have one Qik.

# If you have multiple Qiks, configure each one separately by connecting each one by itself
# to the UART and running this script with device_ids 0, 1, 2, ...
# After all configurations are complete you can reconnect them all to the UART at the same
# time.

import rospy
import time
import serial
import sys
from std_msgs.msg import Float32MultiArray, Float32

device_id = int(sys.argv[1])

if __name__ == "__main__":
    ser = serial.Serial('/dev/qik', 9600)
    #ser.open()
    ser.write(bytearray([0x82]))
    time.sleep(.1)
    print(ser.read())
    time.sleep(.1)
    ser.write(bytearray([0x84, 0, device_id, 0x55, 0x2A]))
    time.sleep(.1)
    print(ser.read())
    ser.write(bytearray([0x84, 1, 0, 0x55, 0x2A]))
    time.sleep(.1)
    print(ser.read())
    ser.write(bytearray([0x84, 2, 1, 0x55, 0x2A]))
    time.sleep(.1)
    print(ser.read())
    ser.write(bytearray([0x84, 3, 1, 0x55, 0x2A]))
    time.sleep(.1)
    print(ser.read())
